### ISSUE TITLE
Possibility to add args to chat_downloader

### ISSUE THREAD

**Issue by Smallinger** [Zibbp/ganymede#119]
Hey, is it possible to add some args to the chat downloader ? like -v for verbose ? a second question is can i save the logs from every action on the queue ? i mean "Video Download", "Video Convert", "Chat Download" and so on for debugging ?.

i got this error on last stream, and in my tmp file there are no json's

```py
Chat downloader started.
It it unlikely that you will see further output in this log.
Traceback (most recent call last): 
File "/usr/local/bin/chat_downloader", line 33, in sys.exit(load_entry_point('chat-downloader==0.2.3', 'console_scripts', 'chat_downloader')()) 
File "/usr/local/lib/python3.9/dist-packages/chat_downloader-0.2.3-py3.9.egg/chat_downloader/cli.py", line 194, in main run(**args.dict) 
File "/usr/local/lib/python3.9/dist-packages/chat_downloader-0.2.3-py3.9.egg/chat_downloader/chat_downloader.py", line 351, in run chat = downloader.get_chat(**chat_params) 
File "/usr/local/lib/python3.9/dist-packages/chat_downloader-0.2.3-py3.9.egg/chat_downloader/chat_downloader.py", line 224, in get_chat chat = get_chat(match, params) 
File "/usr/local/lib/python3.9/dist-packages/chat_downloader-0.2.3-py3.9.egg/chat_downloader/sites/twitch.py", line 1653, in _get_chat_by_stream_id return self.get_chat_by_stream_id(match.group('id'), params) 
File "/usr/local/lib/python3.9/dist-packages/chat_downloader-0.2.3-py3.9.egg/chat_downloader/sites/twitch.py", line 1666, in get_chat_by_stream_id stream_info = self._download_gql(query)[0]['data']['user'] KeyError: 'data'
```

**Comment by Zibbp** [comment]
Thanks for the notification about the chat issue and the update to chat-downloader. I'll do some testing and push a new release that uses the updated version in a bit. The latest TwitchDownloaderCLI release is in a "pre-release" state so I am holding off until that is promoted to an official release.

I can take a look into allow custom chat-downloader arguments. I chose not to do that initially because it would create a log line for each message that is being downloaded which would result in large log files.

> can i save the logs from every action on the queue ? i mean "Video Download", "Video Convert", "Chat Download" and so on for debugging ?

The logs for each task should be available in the mounted `/logs` volume if I'm reading this right.
