### ISSUE TITLE
new livestream feature twitch-chat bugged

### ISSUE THREAD

**Issue by Smallinger** [Zibbp/ganymede#160]
Livestream recording is starting good, but the chat recorder give me these errors.

INF Manually starting task check_live 
TwitchDownloaderCLI for vod chat download | error=signal: aborted

`Unhandled exception. System.AggregateException: One or more errors occurred. (Value was either too large or too small for an Int32.)
---> System.OverflowException: Value was either too large or too small for an Int32.
at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
at System.Number.ParseInt32(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
at System.Int32.Parse(String )
at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
at System.Threading.Tasks.Task.Wait()
at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
at TwitchDownloaderCLI.Program.Main(String[] args)`

**Comment by Smallinger** [comment]
after a fresh install all look like is working.

**Comment by Zibbp** [comment]
I wonder if this is a TwitchDownloader issue or an issue with the convert function. If you see this happen again, can you upload the chat file? The file should now be in the final destination folder after each chat task.
