### ISSUE TITLE
404 on Channel page

### ISSUE THREAD

**Issue by KimPig** [Zibbp/ganymede#268]
I'm getting a 404 error on the Channel page. (https://url/channels/name)
I am using a reverse proxy,

I've seen the same issue before, but it didn't work for me.

There seems to be no problem with docker-compose, is there a solution?

**Comment by Zibbp** [comment]
Post your docker compose along with any errors in the browser console / network tab. It's probably related to the frontend container not being able to connect to the API via the reverse proxy. If you exec into the frontend container, can you curl the API url via reverse proxy? If not, you'll need to fix that.

**Comment by CyferShepard** [comment]
Hi, second on this, im also getting this error. Im also using a reverse proxy, every page works except for this one. Im able to curl the API

**Comment by Zibbp** [comment]
If you exec into the frontend container `docker exec -it ganymede-frontend /bin/bash`. Are you able to curl the API using the reverse proxy URL?

**Comment by N-1412L** [comment]
Hi, I'm facing the same problem as well, everything is working fine except channel page (which will lead to a 404 error).
I'm hosting on localhost, would that be the reason?


```
AxiosError: connect ECONNREFUSED 127.0.0.1:4800
    at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  port: 4800,
  address: '127.0.0.1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111, ......
  
  HTTP API error TypeError: Cannot read properties of undefined (reading 'status')
    at /app/.next/server/chunks/338.js:39:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async useApi (/app/.next/server/chunks/338.js:59:26)
    at async getServerSideProps (/app/.next/server/pages/channels/[channelName].js:331:26)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  port: 4800,
  address: '127.0.0.1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111, ......
  
TypeError: Cannot read properties of undefined (reading 'data')
    at useApi (/app/.next/server/chunks/338.js:69:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getServerSideProps (/app/.next/server/pages/channels/[channelName].js:331:26)```

**Comment by Zibbp** [comment]
Make sure `API_URL` on the frontend container can be reached from *within* the container. If it's localhost the container can't reach that. I'd use the IP of the server instead.

**Comment by Elandrya2711** [comment]
> Make sure `API_URL` on the frontend container can be reached from _within_ the container. If it's localhost the container can't reach that. I'd use the IP of the server instead.

This would be an helpful information on the reverse proxy wiki page.
