### ISSUE TITLE
Unhandled exception during the Chat Download step

### ISSUE THREAD

**Issue by Entrivax** [Zibbp/ganymede#314]
During the Chat Download step, it fails around the end. I managed to have this error on one stream as of now,

Step logs:
```
[STATUS] - Downloading 68%
[STATUS] - Downloading 73%
[STATUS] - Downloading 78%
[STATUS] - Downloading 82%
[STATUS] - Downloading 87%
[STATUS] - Downloading 90%
[STATUS] - Downloading + Embedding ImagesUnhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at TwitchDownloaderCore.TwitchHelper.GetStvEmoteData(Int32 streamerId, List`1 stvResponse, Boolean allowUnlistedEmotes)
at TwitchDownloaderCore.TwitchHelper.GetThirdPartyEmoteData(Int32 streamerId, Boolean getBttv, Boolean getFfz, Boolean getStv, Boolean allowUnlistedEmotes, CancellationToken cancellationToken)
at TwitchDownloaderCore.TwitchHelper.GetThirdPartyEmotes(List`1 comments, Int32 streamerId, String cacheFolder, EmbeddedData embeddedData, Boolean bttv, Boolean ffz, Boolean stv, Boolean allowUnlistedEmotes, Boolean offline, CancellationToken cancellationToken)
at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
at System.Threading.Tasks.Task.Wait()
at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
at TwitchDownloaderCLI.Program.Main(String[] args)
```

API logs:
```json
{"level":"error","error":"signal: aborted","time":"2023-11-20T20:31:44+01:00","message":"error running TwitchDownloaderCLI for vod chat download"}
{"level":"error","error":"signal: aborted","time":"2023-11-20T20:31:44+01:00","message":"error downloading chat"}
```

Ganymede info:
![image](https://github.com/Zibbp/ganymede/assets/1197915/af820260-6816-49bd-bd3d-35c2643ad91f)

Ganymede was deployed with the `latest` tag from the registry.
Also, I managed to download successfully the chat from the faulty stream with the CLI directly on Windows, with TwitchDownloaderCLI 1.53.2 (the same version as for Ganymede) and the same with the 1.53.4.
```sh
> ./TwitchDownloaderCLI.exe chatdownload --id 1980026722 -o chat.json -E
TwitchDownloaderCLI 1.53.2 Copyright (c) 2019 lay295 and contributors
[STATUS] - Downloading 90%
[STATUS] - Downloading + Embedding Images
[STATUS] - Backfilling commenter info
[STATUS] - Writing output file
```

```sh
> ./TwitchDownloaderCLI.exe chatdownload --id 1980026722 -o chat.json -E
TwitchDownloaderCLI 1.53.4 Copyright (c) lay295 and contributors
[STATUS] - Downloading 90%
[STATUS] - Downloading + Embedding Images
[STATUS] - Backfilling commenter info
[STATUS] - Writing output file
```

**Comment by Zibbp** [comment]
I was able to download the chat of `1980026722` on my test instance, running version `TwitchDownloaderCLI 1.53.2`. Can you retry the chat download task again? Are you running the ARM image or x86?

**Comment by Zibbp** [comment]
Ya there's not much to do here, other than retry at another time. I'm in the early stages of re-doing the queue system with retries included for tasks, though it may not help much if you waited two hours in this case.
