### ISSUE TITLE
[BUG] Error clicking archive 

### ISSUE THREAD

**Issue by LostRager** [Zibbp/ganymede#41]
If your the rank "user" and click archive on the home page you get the error in console:

`entry.55e12800.mjs:1 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insert (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:62487)
    at Tt (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:52007)
    at Tt (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:51743)
    at Tt (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:51743)
    at _.transition.afterLeave (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:19007)
    at H (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:52900)
    at R._leaveCb (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:25017)
    at q (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:67905)
    at $ (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:68204)
    at sa (http://10.0.0.113:4801/_nuxt/entry.55e12800.mjs:1:69018)`
![image](https://user-images.githubusercontent.com/5929772/191510104-efa8d87c-7b77-4db9-bee2-e09311c28dba.png)

**Comment by Zibbp** [comment]
Hi,

I'm assuming you are talking about the archive button found on the landing page? I just pushed a commit that hides the button if the user has the "user" rank. Ranks archiver, editor, and admin will be able to see it. I'll try to push a release out later today.

https://github.com/Zibbp/ganymede-frontend/commit/52872d3d9692758ed0db12b5b61f9a0021276d3a
